secret_data:
    secret_example: ENC[AES256_GCM,data:Ul4U6vWfT03pav/WdWs=,iv:cYgeAEV8i/qVsi6P6kRQiu16kxo/rDDnR6KqhBXlWLs=,tag:GJK4KvIo0YK4b7/PvVKYhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-29T19:06:53Z"
    mac: ENC[AES256_GCM,data:U4REIkXm7YxiZ9VpeotfvTVqSccQxc71n1LedjqvXbzuu3LTOIk0jg92bkBhh+/jeSBGJtDf1odaJEAH1ub0Rg3kpTSjQnLl8wBUJ3N5T2pB5MJDSkdVbeG4DJlD5bvNy8EOAHmd/OSBEnUshIg15gacMNvfoBmV6q5KKPNI1TQ=,iv:Vrdk4gd2dGFFIO4YJ42F6rwpaO4QGUH8tgLhwLb2wsA=,tag:u8iCRQhNWimV170SojC8vA==,type:str]
    pgp:
        - created_at: "2023-01-29T19:06:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA886xFBboePvAQwAqEBuPouYakwVvTGkfOeC6wU3aS71f+ALxZJWbTZjXNwm
            xdvRI+ROW6Qch1o+md+ao3MrauEapWlcJ3V8bMAX2Xm35Lyrjxdyp9jzeLZmtcBp
            qgk77AC3bbqy1JyRiOqdUaNL9/TMo5UYiAjS8uzo+Iql6Ov8NKXS6stgM6nPd4Du
            C0VcVRAr/lxPgbEmOKLFz2S9uRwshgdQimdhxGjZbDVHNF340bm9X6WogqR/SrDY
            HP8c+SZj+Pwv0qS4VuIuLiFc8SNETqv0D1MPiZUOVlagvv9n8UWWRMv7UA5dNvqt
            ZNvASZa/Ebeqwylz/y5/jYHOPifo+Q6O4qjX/e+3Yx68H8BOP2R8JsD/W6FiyKyk
            JETf9jj5KuyCuc9LgpUFDHiDpTYL39kHS77xyo8XFBbQhgOsPE1UOWB8OBZnPxAj
            Rl8oAauBQw2FiOM/OOp5lJDR3HFCYn/o2iQq5BpShQ8RMW/bXjIOgg2aP6MHpgE8
            4hmnOTWzISAP/P2V+6o20l4B2+IvgEiWLTG1J65+SzSSIolxXGvYYNcurIggZMPZ
            Gb8+LvYi2UIzpFFD270Z6noK06lGii3ZPzTOv8gI2vo8+Y+4Xc9KObQpfyBtsesK
            22cxPsOHxNFQJ9FMxL/l
            =ilmF
            -----END PGP MESSAGE-----
          fp: 7BC406BAFA125A9357AF29991934F5B53CA30A2E
    unencrypted_suffix: _unencrypted
    version: 3.7.3
